import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,parseSave,defaultSave,WIDTH,HEIGHT} from '../dist/engine.js';

test('ten discrete input events produce exactly ten input actions',()=>{const g=new Game();g.reset();const x=g.player.x;for(let i=0;i<10;i++)g.input('right',false);g.update(0);assert.equal(g.inputActions,10);assert.equal(g.inputEvents,10);assert.equal(g.player.x,x+30);g.update(0);assert.equal(g.inputActions,10);});
test('paused and level-up states freeze game time and world',()=>{const g=new Game();g.reset();g.update(.05);g.pause();const before=JSON.stringify(g);for(let i=0;i<60;i++)g.update(.05);assert.equal(JSON.stringify(g),before);g.resume();g.update(.05);assert.equal(g.time,.1);g.status='upgrade';const t=g.time;g.update(.05);assert.equal(g.time,t);assert.equal(g.upgrade('invalid'),false);assert.equal(g.upgrade('power'),true);assert.equal(g.power,2);});
test('both outcomes emit one record and reset all current-round values',()=>{for(const outcome of ['won','lost']){let calls=0;const g=new Game(()=>calls++);g.reset(2,'B');if(outcome==='won')g.time=29.99;else g.hp=0;g.update(.02);assert.equal(g.status,outcome);g.update(.05);assert.equal(calls,1);g.reset(2,'B');assert.equal(g.status,'playing');assert.equal(g.time,0);assert.equal(g.hp,100);assert.equal(g.score,0);assert.equal(g.level,1);assert.equal(g.enemies.length,0);assert.equal(g.bullets.length,0);assert.equal(g.gems.length,0);assert.equal(g.inputActions,0);assert.equal(g.spawnInterval,.6);}});
test('world bounds clamp movement and diagonals retain normalized speed',()=>{const g=new Game();g.reset();g.move(-9999,-9999);assert.deepEqual(g.player,{x:22,y:32});g.move(9999,9999);assert.deepEqual(g.player,{x:WIDTH-22,y:HEIGHT-22});});
test('only spawn interval differs between A and B with same stage and seed',()=>{const a=new Game(),b=new Game();a.reset(1,'A');b.reset(1,'B');assert.equal(a.rng,b.rng);assert.equal(a.fireInterval,b.fireInterval);assert.equal(a.power,b.power);assert.equal(a.hp,b.hp);assert.equal(a.spawnInterval,.8);assert.equal(b.spawnInterval,.6);a.spawn();b.spawn();assert.deepEqual(a.enemies,b.enemies);});
test('empty, malformed and semantically invalid storage recover',()=>{assert.deepEqual(parseSave(null).data,defaultSave());assert.equal(parseSave('').recovered,false);for(const raw of ['null','{broken','[]',JSON.stringify({...defaultSave(),best:[0,-1,0]}),JSON.stringify({...defaultSave(),records:[{}]})]){const parsed=parseSave(raw);assert.equal(parsed.recovered,true);assert.deepEqual(parsed.data,defaultSave());}});
test('declared records and preferences survive serialize/parse',()=>{const s=defaultSave(true);s.best=[100,20,80];s.difficulty='B';const g=new Game(r=>s.records.push(r));g.reset(0,'B');g.hp=0;g.update(.01);s.decision={stage:0,difficulty:'B',reason:'기록의 중앙값 비교'};assert.deepEqual(parseSave(JSON.stringify(s)).data,s);assert.equal(parseSave(JSON.stringify(s)).recovered,false);});
test('pause during upgrade resumes the pending choice rather than skipping it',()=>{const g=new Game();g.reset();g.status='upgrade';g.pause();assert.equal(g.status,'paused');const snapshot=JSON.stringify(g);g.update(.05);assert.equal(JSON.stringify(g),snapshot);g.resume();assert.equal(g.status,'upgrade');assert.equal(g.upgrade('rate'),true);assert.equal(g.status,'playing');});
test('home abandons a round without a completed play record and resets controls',()=>{let records=0;const g=new Game(()=>records++);g.reset(2,'B');g.input('left');g.update(.05);g.pause();g.home();assert.equal(g.status,'ready');assert.equal(g.stage,0);assert.equal(g.time,0);assert.equal(g.hp,100);assert.equal(g.keys.size,0);assert.equal(g.enemies.length,0);g.update(.05);assert.equal(g.time,0);assert.equal(records,0);});
test('old save migration preserves records but does not mix old experiments',()=>{const old={...defaultSave(),version:1};delete old.unlocked;const g=new Game(r=>old.records.push(r));g.reset(0,'A');g.time=29.99;g.update(.02);delete old.records[0].ruleset;old.decision={stage:0,difficulty:'A',reason:'이전 값'};const {data,recovered}=parseSave(JSON.stringify(old));assert.equal(recovered,false);assert.equal(data.version,2);assert.equal(data.unlocked,2);assert.equal(data.records.length,1);assert.equal(data.records[0].ruleset,1);assert.equal(data.decision,null);const invalid={...data,unlocked:99};assert.equal(parseSave(JSON.stringify(invalid)).recovered,true);});
test('600 seconds of simulated round lifecycle retain finite responsive state',()=>{let runs=0;const g=new Game(()=>runs++);g.reset();for(let i=0;i<36000;i++){if(['won','lost'].includes(g.status))g.reset(i%3,i%2?'A':'B');if(g.status==='upgrade')g.upgrade('power');if(i%60===0)g.input(['up','right','down','left'][Math.floor(i/60)%4],false);g.update(1/60);assert.ok(Number.isFinite(g.player.x)&&Number.isFinite(g.player.y));assert.ok(g.enemies.length<400);assert.ok(g.bullets.length<100);}assert.ok(runs>0);if(g.status==='upgrade')g.upgrade('heal');if(g.status!=='playing')g.reset();const before=g.inputActions;g.input('right',false);g.update(0);assert.equal(g.inputActions,before+1);});
